### ISSUE TITLE
projectOnNavmesh error

### ISSUE THREAD

**Issue by tranlong021988** [wanadev/babylon-navigation-mesh#1]
hi, I'm trying to estimate a position value on navigation mesh using  navigation.projectOnNavmesh , but I get this error 
```
Navigation.js:113 Uncaught TypeError: A.dot is not a function
    at __class__._getProjectionOnNode (Navigation.js:113)
    at __class__.projectOnNavmesh (Navigation.js:87) 
```
I don't know reason why. Do you have any solution for this ?

**Comment by clementlevasseur** [comment]
Yes, I'll fix that right now !
Thanks

**Comment by clementlevasseur** [comment]
@tranlong021988 It is fixed, thanks for the issue

**Comment by tranlong021988** [comment]
hi. Thank you for fix it so fast. But can you do me another favor ? I can not locate ./build/babylon-navigation-mesh.js . I know it was generated by Grunt but I don't know how to build it (I'm designer). Thank you
