### ISSUE TITLE
Navigation is not a constructor 

### ISSUE THREAD

**Issue by tranlong021988** [wanadev/babylon-navigation-mesh#2]
Hi, it's me again, after build Grunt for new source update, the Dot issue has gone and this issue happen:
Uncaught TypeError: Navigation is not a constructor
It happen with current demo, too.

**Comment by clementlevasseur** [comment]
I changed the step in the ReadMe.md,

Did you do all the steps ?

```
git clone git@github.com:wanadev/babylon-navigation-mesh.git
cd babylon-navigation-mesh
npm install grunt-cli
npm install
grunt
```

**Comment by clementlevasseur** [comment]
I will refacto the build system without grunt

**Comment by clementlevasseur** [comment]
Hi !
I changed all the build system without grunt.
So now to build, you just have to npm run build, but the builded file are already in the dist folder.

Please tell me if averything is ok !

**Comment by tranlong021988** [comment]
I downloaded file from dist folder and now it work, but I can not get navigation.projectOnNavmesh working. Here is error:
babylon-navigation-mesh.js:487 Uncaught TypeError: position.projectOnPlane is not a function
    at __class__._getProjectionOnNode (babylon-navigation-mesh.js:487)
    at __class__.projectOnNavmesh (babylon-navigation-mesh.js:460)

**Comment by clementlevasseur** [comment]
I updated the file, please try again.

**Comment by tranlong021988** [comment]
hi, new error appear with navigation.projectOnNavmesh: 
babylon-navigation-mesh.js:477 Uncaught TypeError: proj.subtractInPlace is not a function
    at __class__._projectPointOnPlane (babylon-navigation-mesh.js:477)
    at __class__._getProjectionOnNode (babylon-navigation-mesh.js:495)
    at __class__.projectOnNavmesh (babylon-navigation-mesh.js:460)

**Comment by clementlevasseur** [comment]
I fixed it but this one is weird because this function exist on BABYLON.Vector3. You can try now

**Comment by tranlong021988** [comment]
yeah, sorry. That is my bad. I used wrong parameter. Now it's work ok.  Thank you for your awesome works. I'm using it for a indie game project. Still building but if you wanna take a look: 
http://appsbymekong.com/flashdemo/maze/
The naked guy chasing you with navmesh AI system.  You can move by using Virtual Joystick(Taping Right-Left screen side). 
Thank you again.

**Comment by clementlevasseur** [comment]
That nice ! 
Don't hesitate to ask new feature, I can plan to do it later !
